version: '3.8'

services:
  backend:
  build:
    context: ./backend_rds
  container_name: backend
  restart: always
  environment:
    DB_NAME: test_db
    DB_USER: test_user
    DB_PASSWORD: test_password
    DB_HOST: postgres
    DB_PORT: 5432
  ports:
    - "8000:8000"
  depends_on:
    - postgres


    postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_user"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
