version: '3.8'

services:
  backend:
    build: ./backend_rds
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend_rds:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=your_db
      - DB_USER=your_user
      - DB_PASSWORD=your_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
