name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Check out the code
        uses: actions/checkout@v3

      # Шаг 2: Подключение к EC2 и деплой
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY }}" ec2-user@18.193.161.41 << 'EOF'
          cd /home/ec2-user/book-sales-platform
          docker-compose down
          docker-compose up -d
          EOF
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
