name: Debug EC2 SSH Connection

on:
  workflow_dispatch: # Запускается вручную для тестирования

jobs:
  debug-ssh:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируйте репозиторий
      - name: Check out repository
        uses: actions/checkout@v3

      # Шаг 2: Сохраните SSH-ключ из секрета в файл
      - name: Save EC2 SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > debug.pem
          chmod 600 debug.pem

      # Шаг 3: Проверьте содержимое ключа
      - name: Verify SSH Key
        run: cat debug.pem

      # Шаг 4: Попробуйте подключиться к инстансу
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i debug.pem ec2-user@18.193.161.41 << 'EOF'
          echo "Successfully connected to EC2 instance!"
          EOF
