name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Update and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd || true  # Удалить конфликтующий пакет
          sudo apt-get install -y containerd.io     # Установить нужный пакет
