name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируйте репозиторий
      - name: Check out the repository
        uses: actions/checkout@v3

      # Шаг 2: Создайте файл с ключом
      - name: Create SSH key file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > EC2Tutorial.pem
          chmod 600 EC2Tutorial.pem

      # Шаг 3: Подключитесь к EC2 и выполните деплой
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i EC2Tutorial.pem ec2-user@18.193.161.41 << 'EOF'
          echo "Connecting to EC2 instance..."
          cd /home/ec2-user/book-sales-platform || exit 1
          echo "Pulling latest changes from GitHub..."
          git pull origin main || exit 1
          echo "Stopping existing containers..."
          docker-compose down || exit 1
          echo "Starting updated containers..."
          docker-compose up -d || exit 1
          echo "Deployment completed successfully!"
          EOF
